import type { WorkoutPlan, WorkoutSession, WorkoutHistorySummary } from '@/types/app';

export const MOCK_PLAN: WorkoutPlan = {
  id: 'plan-1',
  user_id: 'mock-user-1',
  name: 'Push / Pull / Legs — Intermediate',
  goal: 'build_muscle',
  version: 1,
  is_active: true,
  created_at: '2026-01-20T00:00:00Z',
  workout_plan_days: [
    {
      id: 'day-1',
      plan_id: 'plan-1',
      day_of_week: 'monday',
      day_name: 'Push — Chest & Shoulders',
      order_index: 0,
      estimated_minutes: 50,
      plan_exercises: [
        {
          id: 'pe-1',
          plan_day_id: 'day-1',
          exercise_id: 'ex-bench',
          exercise: {
            id: 'ex-bench',
            name: 'Bench Press',
            muscle_groups: ['chest', 'triceps', 'shoulders'],
            equipment_required: ['barbell'],
            difficulty: 'intermediate',
            instructions:
              'Lie on bench, grip slightly wider than shoulder width, lower bar to chest, press up.',
            video_url: null,
          },
          sets: 4,
          reps: '6-8',
          rest_seconds: 120,
          order_index: 0,
          notes: 'Focus on chest squeeze at top',
        },
        {
          id: 'pe-2',
          plan_day_id: 'day-1',
          exercise_id: 'ex-ohp',
          exercise: {
            id: 'ex-ohp',
            name: 'Overhead Press',
            muscle_groups: ['shoulders', 'triceps'],
            equipment_required: ['barbell'],
            difficulty: 'intermediate',
            instructions:
              'Stand with bar at shoulder height, press directly overhead, lock out elbows.',
            video_url: null,
          },
          sets: 3,
          reps: '8-10',
          rest_seconds: 90,
          order_index: 1,
          notes: null,
        },
        {
          id: 'pe-3',
          plan_day_id: 'day-1',
          exercise_id: 'ex-incline',
          exercise: {
            id: 'ex-incline',
            name: 'Incline DB Press',
            muscle_groups: ['chest', 'shoulders'],
            equipment_required: ['dumbbells'],
            difficulty: 'intermediate',
            instructions: 'Set bench to 30-45 degrees, press dumbbells up and slightly inward.',
            video_url: null,
          },
          sets: 3,
          reps: '10-12',
          rest_seconds: 90,
          order_index: 2,
          notes: null,
        },
        {
          id: 'pe-4',
          plan_day_id: 'day-1',
          exercise_id: 'ex-lateral',
          exercise: {
            id: 'ex-lateral',
            name: 'Lateral Raises',
            muscle_groups: ['shoulders'],
            equipment_required: ['dumbbells'],
            difficulty: 'beginner',
            instructions:
              'Raise dumbbells to the side until parallel with ground, control the descent.',
            video_url: null,
          },
          sets: 4,
          reps: '12-15',
          rest_seconds: 60,
          order_index: 3,
          notes: 'Keep slight bend in elbows',
        },
        {
          id: 'pe-5',
          plan_day_id: 'day-1',
          exercise_id: 'ex-tricep',
          exercise: {
            id: 'ex-tricep',
            name: 'Tricep Pushdowns',
            muscle_groups: ['triceps'],
            equipment_required: ['gym'],
            difficulty: 'beginner',
            instructions:
              'Using cable machine, press the bar down while keeping elbows fixed at sides.',
            video_url: null,
          },
          sets: 3,
          reps: '12-15',
          rest_seconds: 60,
          order_index: 4,
          notes: null,
        },
      ],
    },
    {
      id: 'day-2',
      plan_id: 'plan-1',
      day_of_week: 'tuesday',
      day_name: 'Pull — Back & Biceps',
      order_index: 1,
      estimated_minutes: 50,
      plan_exercises: [
        {
          id: 'pe-6',
          plan_day_id: 'day-2',
          exercise_id: 'ex-pullup',
          exercise: {
            id: 'ex-pullup',
            name: 'Pull-ups',
            muscle_groups: ['back', 'biceps'],
            equipment_required: ['pull_up_bar'],
            difficulty: 'intermediate',
            instructions: 'Hang from bar, pull chest up to bar, lower under control.',
            video_url: null,
          },
          sets: 4,
          reps: '6-10',
          rest_seconds: 120,
          order_index: 0,
          notes: 'Add weight when you can do 10+ reps',
        },
        {
          id: 'pe-7',
          plan_day_id: 'day-2',
          exercise_id: 'ex-row',
          exercise: {
            id: 'ex-row',
            name: 'Barbell Row',
            muscle_groups: ['back', 'biceps'],
            equipment_required: ['barbell'],
            difficulty: 'intermediate',
            instructions: 'Hinge at hips, pull barbell to lower chest, squeeze shoulder blades.',
            video_url: null,
          },
          sets: 4,
          reps: '8-10',
          rest_seconds: 90,
          order_index: 1,
          notes: null,
        },
      ],
    },
    {
      id: 'day-3',
      plan_id: 'plan-1',
      day_of_week: 'thursday',
      day_name: 'Legs — Quads & Hamstrings',
      order_index: 2,
      estimated_minutes: 55,
      plan_exercises: [
        {
          id: 'pe-8',
          plan_day_id: 'day-3',
          exercise_id: 'ex-squat',
          exercise: {
            id: 'ex-squat',
            name: 'Barbell Squat',
            muscle_groups: ['legs', 'glutes'],
            equipment_required: ['barbell'],
            difficulty: 'intermediate',
            instructions: 'Bar on upper back, squat below parallel, drive through heels to stand.',
            video_url: null,
          },
          sets: 4,
          reps: '5-8',
          rest_seconds: 150,
          order_index: 0,
          notes: 'King of all exercises',
        },
      ],
    },
  ],
};

export const MOCK_TODAY_SESSION: WorkoutSession = {
  id: 'session-today',
  user_id: 'mock-user-1',
  plan_day_id: 'day-1',
  day_name: 'Push — Chest & Shoulders',
  status: 'in_progress',
  started_at: new Date().toISOString(),
  completed_at: null,
  duration_seconds: null,
  session_exercises: MOCK_PLAN.workout_plan_days[0].plan_exercises.map((pe, i) => ({
    id: `se-${i}`,
    session_id: 'session-today',
    exercise_id: pe.exercise_id,
    exercise_name: pe.exercise.name,
    planned_sets: pe.sets,
    planned_reps: pe.reps,
    completed_sets:
      i < 2
        ? Array.from({ length: pe.sets }, (_, j) => ({
            set_number: j + 1,
            reps_completed: 8,
            weight_kg: 60,
            rpe: null as number | null,
            rest_seconds: null as number | null,
            completed_at: new Date().toISOString(),
          }))
        : [],
    notes: pe.notes,
    is_skipped: false,
  })),
};

const MOCK_COMPLETED_WORKOUTS: WorkoutSession[] = [
  {
    ...MOCK_TODAY_SESSION,
    id: 'session-complete-1',
    status: 'completed',
    started_at: new Date(Date.now() - (3 * 24 * 3600_000 + 50 * 60_000)).toISOString(),
    completed_at: new Date(Date.now() - 3 * 24 * 3600_000).toISOString(),
    duration_seconds: 3000,
  },
  {
    ...MOCK_TODAY_SESSION,
    id: 'session-complete-2',
    status: 'completed',
    started_at: new Date(Date.now() - (8 * 24 * 3600_000 + 45 * 60_000)).toISOString(),
    completed_at: new Date(Date.now() - 8 * 24 * 3600_000).toISOString(),
    duration_seconds: 2700,
  },
];

export const MOCK_WORKOUT_HISTORY: WorkoutHistorySummary = {
  recent_sessions: MOCK_COMPLETED_WORKOUTS,
  completed_this_week: 1,
  weekly_target: 5,
  adherence_pct: 20,
  last_completed_at: MOCK_COMPLETED_WORKOUTS[0].completed_at,
  total_completed_sessions: MOCK_COMPLETED_WORKOUTS.length,
  average_duration_seconds: 2850,
};
