import type {
  UserProfile,
  WorkoutPlan,
  WorkoutSession,
  FoodLog,
  CoachMessage,
  DailyNutritionSummary,
  WeightLog,
  WorkoutHistorySummary,
  FoodSearchResult,
} from '@/types/app';

export const MOCK_PROFILE: UserProfile = {
  id: 'mock-user-1',
  email: 'arjun@navya.app',
  full_name: 'Arjun Sharma',
  avatar_url: null,
  age_range: '25-34',
  gender: 'male',
  weight_kg: 78,
  height_cm: 178,
  goal: 'build_muscle',
  activity_level: 'moderately_active',
  experience_level: 'intermediate',
  diet_preference: 'high_protein',
  equipment: ['gym', 'dumbbells', 'barbell'],
  workouts_per_week: 5,
  country: 'AU',
  onboarding_complete: true,
  glow_focus: 'Body',
  created_at: '2026-01-15T00:00:00Z',
  updated_at: '2026-03-11T00:00:00Z',
};

export const MOCK_PLAN: WorkoutPlan = {
  id: 'plan-1',
  user_id: 'mock-user-1',
  name: 'Push / Pull / Legs — Intermediate',
  goal: 'build_muscle',
  version: 1,
  is_active: true,
  created_at: '2026-01-20T00:00:00Z',
  workout_plan_days: [
    {
      id: 'day-1',
      plan_id: 'plan-1',
      day_of_week: 'monday',
      day_name: 'Push — Chest & Shoulders',
      order_index: 0,
      estimated_minutes: 50,
      plan_exercises: [
        {
          id: 'pe-1',
          plan_day_id: 'day-1',
          exercise_id: 'ex-bench',
          exercise: {
            id: 'ex-bench',
            name: 'Bench Press',
            muscle_groups: ['chest', 'triceps', 'shoulders'],
            equipment_required: ['barbell'],
            difficulty: 'intermediate',
            instructions:
              'Lie on bench, grip slightly wider than shoulder width, lower bar to chest, press up.',
            video_url: null,
          },
          sets: 4,
          reps: '6-8',
          rest_seconds: 120,
          order_index: 0,
          notes: 'Focus on chest squeeze at top',
        },
        {
          id: 'pe-2',
          plan_day_id: 'day-1',
          exercise_id: 'ex-ohp',
          exercise: {
            id: 'ex-ohp',
            name: 'Overhead Press',
            muscle_groups: ['shoulders', 'triceps'],
            equipment_required: ['barbell'],
            difficulty: 'intermediate',
            instructions:
              'Stand with bar at shoulder height, press directly overhead, lock out elbows.',
            video_url: null,
          },
          sets: 3,
          reps: '8-10',
          rest_seconds: 90,
          order_index: 1,
          notes: null,
        },
        {
          id: 'pe-3',
          plan_day_id: 'day-1',
          exercise_id: 'ex-incline',
          exercise: {
            id: 'ex-incline',
            name: 'Incline DB Press',
            muscle_groups: ['chest', 'shoulders'],
            equipment_required: ['dumbbells'],
            difficulty: 'intermediate',
            instructions: 'Set bench to 30-45 degrees, press dumbbells up and slightly inward.',
            video_url: null,
          },
          sets: 3,
          reps: '10-12',
          rest_seconds: 90,
          order_index: 2,
          notes: null,
        },
        {
          id: 'pe-4',
          plan_day_id: 'day-1',
          exercise_id: 'ex-lateral',
          exercise: {
            id: 'ex-lateral',
            name: 'Lateral Raises',
            muscle_groups: ['shoulders'],
            equipment_required: ['dumbbells'],
            difficulty: 'beginner',
            instructions:
              'Raise dumbbells to the side until parallel with ground, control the descent.',
            video_url: null,
          },
          sets: 4,
          reps: '12-15',
          rest_seconds: 60,
          order_index: 3,
          notes: 'Keep slight bend in elbows',
        },
        {
          id: 'pe-5',
          plan_day_id: 'day-1',
          exercise_id: 'ex-tricep',
          exercise: {
            id: 'ex-tricep',
            name: 'Tricep Pushdowns',
            muscle_groups: ['triceps'],
            equipment_required: ['gym'],
            difficulty: 'beginner',
            instructions:
              'Using cable machine, press the bar down while keeping elbows fixed at sides.',
            video_url: null,
          },
          sets: 3,
          reps: '12-15',
          rest_seconds: 60,
          order_index: 4,
          notes: null,
        },
      ],
    },
    {
      id: 'day-2',
      plan_id: 'plan-1',
      day_of_week: 'tuesday',
      day_name: 'Pull — Back & Biceps',
      order_index: 1,
      estimated_minutes: 50,
      plan_exercises: [
        {
          id: 'pe-6',
          plan_day_id: 'day-2',
          exercise_id: 'ex-pullup',
          exercise: {
            id: 'ex-pullup',
            name: 'Pull-ups',
            muscle_groups: ['back', 'biceps'],
            equipment_required: ['pull_up_bar'],
            difficulty: 'intermediate',
            instructions: 'Hang from bar, pull chest up to bar, lower under control.',
            video_url: null,
          },
          sets: 4,
          reps: '6-10',
          rest_seconds: 120,
          order_index: 0,
          notes: 'Add weight when you can do 10+ reps',
        },
        {
          id: 'pe-7',
          plan_day_id: 'day-2',
          exercise_id: 'ex-row',
          exercise: {
            id: 'ex-row',
            name: 'Barbell Row',
            muscle_groups: ['back', 'biceps'],
            equipment_required: ['barbell'],
            difficulty: 'intermediate',
            instructions: 'Hinge at hips, pull barbell to lower chest, squeeze shoulder blades.',
            video_url: null,
          },
          sets: 4,
          reps: '8-10',
          rest_seconds: 90,
          order_index: 1,
          notes: null,
        },
      ],
    },
    {
      id: 'day-3',
      plan_id: 'plan-1',
      day_of_week: 'thursday',
      day_name: 'Legs — Quads & Hamstrings',
      order_index: 2,
      estimated_minutes: 55,
      plan_exercises: [
        {
          id: 'pe-8',
          plan_day_id: 'day-3',
          exercise_id: 'ex-squat',
          exercise: {
            id: 'ex-squat',
            name: 'Barbell Squat',
            muscle_groups: ['legs', 'glutes'],
            equipment_required: ['barbell'],
            difficulty: 'intermediate',
            instructions: 'Bar on upper back, squat below parallel, drive through heels to stand.',
            video_url: null,
          },
          sets: 4,
          reps: '5-8',
          rest_seconds: 150,
          order_index: 0,
          notes: 'King of all exercises',
        },
      ],
    },
  ],
};

export const MOCK_TODAY_SESSION: WorkoutSession = {
  id: 'session-today',
  user_id: 'mock-user-1',
  plan_day_id: 'day-1',
  day_name: 'Push — Chest & Shoulders',
  status: 'in_progress',
  started_at: new Date().toISOString(),
  completed_at: null,
  duration_seconds: null,
  session_exercises: MOCK_PLAN.workout_plan_days[0].plan_exercises.map((pe, i) => ({
    id: `se-${i}`,
    session_id: 'session-today',
    exercise_id: pe.exercise_id,
    exercise_name: pe.exercise.name,
    planned_sets: pe.sets,
    planned_reps: pe.reps,
    completed_sets:
      i < 2
        ? Array.from({ length: pe.sets }, (_, j) => ({
            set_number: j + 1,
            reps_completed: 8,
            weight_kg: 60,
            completed_at: new Date().toISOString(),
          }))
        : [],
    notes: pe.notes,
    is_skipped: false,
  })),
};

const MOCK_FOOD_LOGS: FoodLog[] = [
  {
    id: 'food-1',
    user_id: 'mock-user-1',
    meal_name: 'Oats with Banana & Honey',
    calories: 380,
    protein_g: 12,
    carbs_g: 68,
    fat_g: 6,
    meal_time: 'breakfast',
    logged_at: new Date(Date.now() - 5 * 3600_000).toISOString(),
    notes: null,
    source: 'manual',
    source_food_id: null,
    custom_food_id: null,
    quantity: 1,
    serving_label: '1 bowl',
    serving_grams: 280,
    is_custom: false,
    updated_at: new Date(Date.now() - 5 * 3600_000).toISOString(),
    deleted_at: null,
  },
  {
    id: 'food-2',
    user_id: 'mock-user-1',
    meal_name: 'Chicken Rice Bowl',
    calories: 620,
    protein_g: 48,
    carbs_g: 65,
    fat_g: 12,
    meal_time: 'lunch',
    logged_at: new Date(Date.now() - 2 * 3600_000).toISOString(),
    notes: null,
    source: 'usda_foundation',
    source_food_id: 'foundation-534358',
    custom_food_id: null,
    quantity: 1,
    serving_label: '1 bowl',
    serving_grams: 340,
    is_custom: false,
    updated_at: new Date(Date.now() - 2 * 3600_000).toISOString(),
    deleted_at: null,
  },
  {
    id: 'food-3',
    user_id: 'mock-user-1',
    meal_name: 'Whey Protein Shake',
    calories: 180,
    protein_g: 30,
    carbs_g: 8,
    fat_g: 3,
    meal_time: 'snack',
    logged_at: new Date(Date.now() - 1 * 3600_000).toISOString(),
    notes: null,
    source: 'manual',
    source_food_id: null,
    custom_food_id: 'custom-food-1',
    quantity: 1,
    serving_label: '1 scoop',
    serving_grams: 35,
    is_custom: true,
    updated_at: new Date(Date.now() - 1 * 3600_000).toISOString(),
    deleted_at: null,
  },
];

export const MOCK_DAILY_NUTRITION: DailyNutritionSummary = {
  date: new Date().toISOString().split('T')[0],
  total_calories: 1180,
  total_protein_g: 90,
  total_carbs_g: 141,
  total_fat_g: 21,
  calorie_goal: 2600,
  protein_goal_g: 156,
  water_total_ml: 1500,
  water_goal_ml: 2500,
  meals: MOCK_FOOD_LOGS,
  recent_foods: [
    {
      id: 'recent-food-1',
      meal_name: 'Chicken Rice Bowl',
      calories: 620,
      protein_g: 48,
      carbs_g: 65,
      fat_g: 12,
      meal_time: 'lunch',
      source: 'usda_foundation',
      source_food_id: 'foundation-534358',
      custom_food_id: null,
      quantity: 1,
      serving_label: '1 bowl',
      serving_grams: 340,
      is_custom: false,
      last_logged_at: new Date(Date.now() - 24 * 3600_000).toISOString(),
    },
    {
      id: 'recent-food-2',
      meal_name: 'Whey Protein Shake',
      calories: 180,
      protein_g: 30,
      carbs_g: 8,
      fat_g: 3,
      meal_time: 'snack',
      source: 'manual',
      source_food_id: null,
      custom_food_id: 'custom-food-1',
      quantity: 1,
      serving_label: '1 scoop',
      serving_grams: 35,
      is_custom: true,
      last_logged_at: new Date(Date.now() - 2 * 24 * 3600_000).toISOString(),
    },
  ],
  favorite_foods: [
    {
      id: 'favorite-food-1',
      user_id: 'mock-user-1',
      source: 'usda_foundation',
      source_food_id: 'foundation-534358',
      custom_food_id: null,
      food_name: 'Chicken Rice Bowl',
      category: 'Mixed dishes',
      calories: 620,
      protein_g: 48,
      carbs_g: 65,
      fat_g: 12,
      default_serving_label: '1 bowl',
      default_serving_grams: 340,
      created_at: new Date(Date.now() - 3 * 24 * 3600_000).toISOString(),
      updated_at: new Date(Date.now() - 3 * 24 * 3600_000).toISOString(),
      deleted_at: null,
    },
  ],
  water_logs: [
    {
      id: 'water-1',
      user_id: 'mock-user-1',
      amount_ml: 500,
      logged_at: new Date(Date.now() - 8 * 3600_000).toISOString(),
    },
    {
      id: 'water-2',
      user_id: 'mock-user-1',
      amount_ml: 1000,
      logged_at: new Date(Date.now() - 3 * 3600_000).toISOString(),
    },
  ],
};

export const MOCK_COACH_MESSAGES: CoachMessage[] = [
  {
    id: 'msg-1',
    user_id: 'mock-user-1',
    action_type: 'daily_insight',
    role: 'coach',
    text: "Great 7-day streak Arjun! 🔥 Your push session today is looking solid. You're tracking 2 reps ahead of last week on bench — keep that progressive overload coming.",
    created_at: new Date(Date.now() - 30 * 60_000).toISOString(),
  },
  {
    id: 'msg-2',
    user_id: 'mock-user-1',
    action_type: 'quick_reply',
    role: 'user',
    text: 'My shoulder feels a bit tight today',
    created_at: new Date(Date.now() - 25 * 60_000).toISOString(),
  },
  {
    id: 'msg-3',
    user_id: 'mock-user-1',
    action_type: 'adjust_workout',
    role: 'coach',
    text: "Got it. Swap OHP for lateral raises today — same shoulder engagement, much lower joint stress. Stretch your pecs for 90s before starting. You're still on track for your weekly volume target.",
    created_at: new Date(Date.now() - 20 * 60_000).toISOString(),
  },
];

export const MOCK_WEIGHT_LOGS: WeightLog[] = [
  {
    id: 'weight-1',
    user_id: 'mock-user-1',
    weight_kg: 80.1,
    logged_at: new Date(Date.now() - 14 * 24 * 3600_000).toISOString(),
  },
  {
    id: 'weight-2',
    user_id: 'mock-user-1',
    weight_kg: 79.6,
    logged_at: new Date(Date.now() - 7 * 24 * 3600_000).toISOString(),
  },
  {
    id: 'weight-3',
    user_id: 'mock-user-1',
    weight_kg: 79.1,
    logged_at: new Date(Date.now() - 24 * 3600_000).toISOString(),
  },
];

const MOCK_COMPLETED_WORKOUTS: WorkoutSession[] = [
  {
    ...MOCK_TODAY_SESSION,
    id: 'session-complete-1',
    status: 'completed',
    started_at: new Date(Date.now() - (3 * 24 * 3600_000 + 50 * 60_000)).toISOString(),
    completed_at: new Date(Date.now() - 3 * 24 * 3600_000).toISOString(),
    duration_seconds: 3000,
  },
  {
    ...MOCK_TODAY_SESSION,
    id: 'session-complete-2',
    status: 'completed',
    started_at: new Date(Date.now() - (8 * 24 * 3600_000 + 45 * 60_000)).toISOString(),
    completed_at: new Date(Date.now() - 8 * 24 * 3600_000).toISOString(),
    duration_seconds: 2700,
  },
];

export const MOCK_WORKOUT_HISTORY: WorkoutHistorySummary = {
  recent_sessions: MOCK_COMPLETED_WORKOUTS,
  completed_this_week: 1,
  weekly_target: 5,
  adherence_pct: 20,
  last_completed_at: MOCK_COMPLETED_WORKOUTS[0].completed_at,
  total_completed_sessions: MOCK_COMPLETED_WORKOUTS.length,
  average_duration_seconds: 2850,
};

export const COACH_QUICK_REPLIES = [
  "Modify today's workout",
  'Suggest a meal',
  "How's my progress?",
  "I'm sore today",
  'Give me a tip',
];

export const DEMO_COACH_RESPONSES = [
  "Based on your recent sessions, you're consistently hitting your volume targets. Keep the intensity on compound movements and you'll see solid strength gains in the next 2–3 weeks. 💪",
  "For muscle building, aim for 1.8–2.2g of protein per kg of body weight. At 78kg that's 140–172g/day. Your current intake looks close — just bump up dinner protein.",
  'Rest day tomorrow? Perfect. Light walking and 8 hours of sleep will accelerate recovery more than any supplement. Your body grows during rest, not just during training.',
  "Your 7-day streak is a strong habit signal. The hardest part was week 1 — you're well past that now. Stay consistent for another 3 weeks and this becomes automatic.",
  "For today's soreness: focus on active recovery — 10 min light cardio, dynamic stretching, and foam rolling the affected areas. Avoid training that muscle group for another 24–48 hours.",
];

export const MOCK_FOOD_SEARCH_RESULTS: FoodSearchResult[] = [
  {
    id: 'mock-search-1',
    source: 'usda_foundation',
    source_food_id: 'foundation-534358',
    custom_food_id: null,
    name: 'Chicken Breast, grilled',
    category: 'Poultry Products',
    data_version: 'usda_fdc_2026_04_mvp',
    calories_per_100g: 165,
    protein_g_per_100g: 31,
    carbs_g_per_100g: 0,
    fat_g_per_100g: 3.6,
    default_serving_label: '1 breast',
    default_serving_grams: 172,
    default_nutrients: {
      calories: 284,
      protein_g: 53.3,
      carbs_g: 0,
      fat_g: 6.2,
    },
    portions: [
      {
        id: 'portion-1',
        food_id: 'mock-search-1',
        amount: 1,
        unit: 'breast',
        modifier: null,
        gram_weight: 172,
        label: '1 breast (172g)',
        is_default: true,
      },
      {
        id: 'portion-2',
        food_id: 'mock-search-1',
        amount: 100,
        unit: 'g',
        modifier: null,
        gram_weight: 100,
        label: '100g',
        is_default: false,
      },
    ],
    is_custom: false,
    is_favorite: true,
  },
  {
    id: 'mock-search-2',
    source: 'usda_foundation',
    source_food_id: 'foundation-1102653',
    custom_food_id: null,
    name: 'Brown Rice, cooked',
    category: 'Grains and Pasta',
    data_version: 'usda_fdc_2026_04_mvp',
    calories_per_100g: 123,
    protein_g_per_100g: 2.7,
    carbs_g_per_100g: 25.6,
    fat_g_per_100g: 1,
    default_serving_label: '1 cup',
    default_serving_grams: 195,
    default_nutrients: {
      calories: 240,
      protein_g: 5.3,
      carbs_g: 50,
      fat_g: 2,
    },
    portions: [
      {
        id: 'portion-3',
        food_id: 'mock-search-2',
        amount: 1,
        unit: 'cup',
        modifier: null,
        gram_weight: 195,
        label: '1 cup (195g)',
        is_default: true,
      },
    ],
    is_custom: false,
    is_favorite: false,
  },
  {
    id: 'mock-search-3',
    source: 'manual',
    source_food_id: null,
    custom_food_id: 'custom-food-1',
    name: 'My Special Protein Shake',
    category: 'Custom food',
    data_version: 'usda_fdc_2026_04_mvp',
    calories_per_100g: 450,
    protein_g_per_100g: 80,
    carbs_g_per_100g: 10,
    fat_g_per_100g: 5,
    default_serving_label: '1 scoop',
    default_serving_grams: 35,
    default_nutrients: {
      calories: 157,
      protein_g: 28,
      carbs_g: 3.5,
      fat_g: 1.7,
    },
    portions: [
      {
        id: 'portion-4',
        food_id: 'custom-food-1',
        amount: 1,
        unit: 'scoop',
        modifier: null,
        gram_weight: 35,
        label: '1 scoop (35g)',
        is_default: true,
      },
    ],
    is_custom: true,
    is_favorite: false,
  },
];
