import type { FoodLog, DailyNutritionSummary, FoodSearchResult } from '@/types/app';

const MOCK_FOOD_LOGS: FoodLog[] = [
  {
    id: 'food-1',
    user_id: 'mock-user-1',
    meal_name: 'Oats with Banana & Honey',
    calories: 380,
    protein_g: 12,
    carbs_g: 68,
    fat_g: 6,
    meal_time: 'breakfast',
    logged_at: new Date(Date.now() - 5 * 3600_000).toISOString(),
    notes: null,
    source: 'manual',
    source_food_id: null,
    custom_food_id: null,
    quantity: 1,
    serving_label: '1 bowl',
    serving_grams: 280,
    is_custom: false,
    updated_at: new Date(Date.now() - 5 * 3600_000).toISOString(),
    deleted_at: null,
  },
  {
    id: 'food-2',
    user_id: 'mock-user-1',
    meal_name: 'Chicken Rice Bowl',
    calories: 620,
    protein_g: 48,
    carbs_g: 65,
    fat_g: 12,
    meal_time: 'lunch',
    logged_at: new Date(Date.now() - 2 * 3600_000).toISOString(),
    notes: null,
    source: 'usda_foundation',
    source_food_id: 'foundation-534358',
    custom_food_id: null,
    quantity: 1,
    serving_label: '1 bowl',
    serving_grams: 340,
    is_custom: false,
    updated_at: new Date(Date.now() - 2 * 3600_000).toISOString(),
    deleted_at: null,
  },
  {
    id: 'food-3',
    user_id: 'mock-user-1',
    meal_name: 'Whey Protein Shake',
    calories: 180,
    protein_g: 30,
    carbs_g: 8,
    fat_g: 3,
    meal_time: 'snack',
    logged_at: new Date(Date.now() - 1 * 3600_000).toISOString(),
    notes: null,
    source: 'manual',
    source_food_id: null,
    custom_food_id: 'custom-food-1',
    quantity: 1,
    serving_label: '1 scoop',
    serving_grams: 35,
    is_custom: true,
    updated_at: new Date(Date.now() - 1 * 3600_000).toISOString(),
    deleted_at: null,
  },
];

export const MOCK_DAILY_NUTRITION: DailyNutritionSummary = {
  date: new Date().toISOString().split('T')[0],
  total_calories: 1180,
  total_protein_g: 90,
  total_carbs_g: 141,
  total_fat_g: 21,
  calorie_goal: 2600,
  protein_goal_g: 156,
  water_total_ml: 1500,
  water_goal_ml: 2500,
  meals: MOCK_FOOD_LOGS,
  recent_foods: [
    {
      id: 'recent-food-1',
      meal_name: 'Chicken Rice Bowl',
      calories: 620,
      protein_g: 48,
      carbs_g: 65,
      fat_g: 12,
      meal_time: 'lunch',
      source: 'usda_foundation',
      source_food_id: 'foundation-534358',
      custom_food_id: null,
      quantity: 1,
      serving_label: '1 bowl',
      serving_grams: 340,
      is_custom: false,
      last_logged_at: new Date(Date.now() - 24 * 3600_000).toISOString(),
    },
    {
      id: 'recent-food-2',
      meal_name: 'Whey Protein Shake',
      calories: 180,
      protein_g: 30,
      carbs_g: 8,
      fat_g: 3,
      meal_time: 'snack',
      source: 'manual',
      source_food_id: null,
      custom_food_id: 'custom-food-1',
      quantity: 1,
      serving_label: '1 scoop',
      serving_grams: 35,
      is_custom: true,
      last_logged_at: new Date(Date.now() - 2 * 24 * 3600_000).toISOString(),
    },
  ],
  favorite_foods: [
    {
      id: 'favorite-food-1',
      user_id: 'mock-user-1',
      source: 'usda_foundation',
      source_food_id: 'foundation-534358',
      custom_food_id: null,
      food_name: 'Chicken Rice Bowl',
      category: 'Mixed dishes',
      calories: 620,
      protein_g: 48,
      carbs_g: 65,
      fat_g: 12,
      default_serving_label: '1 bowl',
      default_serving_grams: 340,
      created_at: new Date(Date.now() - 3 * 24 * 3600_000).toISOString(),
      updated_at: new Date(Date.now() - 3 * 24 * 3600_000).toISOString(),
      deleted_at: null,
    },
  ],
  water_logs: [
    {
      id: 'water-1',
      user_id: 'mock-user-1',
      amount_ml: 500,
      logged_at: new Date(Date.now() - 8 * 3600_000).toISOString(),
    },
    {
      id: 'water-2',
      user_id: 'mock-user-1',
      amount_ml: 1000,
      logged_at: new Date(Date.now() - 3 * 3600_000).toISOString(),
    },
  ],
};

export const MOCK_FOOD_SEARCH_RESULTS: FoodSearchResult[] = [
  {
    id: 'mock-search-1',
    source: 'usda_foundation',
    source_food_id: 'foundation-534358',
    custom_food_id: null,
    name: 'Chicken Breast, grilled',
    category: 'Poultry Products',
    data_version: 'usda_fdc_2026_04_mvp',
    calories_per_100g: 165,
    protein_g_per_100g: 31,
    carbs_g_per_100g: 0,
    fat_g_per_100g: 3.6,
    default_serving_label: '1 breast',
    default_serving_grams: 172,
    default_nutrients: {
      calories: 284,
      protein_g: 53.3,
      carbs_g: 0,
      fat_g: 6.2,
    },
    portions: [
      {
        id: 'portion-1',
        food_id: 'mock-search-1',
        amount: 1,
        unit: 'breast',
        modifier: null,
        gram_weight: 172,
        label: '1 breast (172g)',
        is_default: true,
      },
      {
        id: 'portion-2',
        food_id: 'mock-search-1',
        amount: 100,
        unit: 'g',
        modifier: null,
        gram_weight: 100,
        label: '100g',
        is_default: false,
      },
    ],
    is_custom: false,
    is_favorite: true,
  },
  {
    id: 'mock-search-2',
    source: 'usda_foundation',
    source_food_id: 'foundation-1102653',
    custom_food_id: null,
    name: 'Brown Rice, cooked',
    category: 'Grains and Pasta',
    data_version: 'usda_fdc_2026_04_mvp',
    calories_per_100g: 123,
    protein_g_per_100g: 2.7,
    carbs_g_per_100g: 25.6,
    fat_g_per_100g: 1,
    default_serving_label: '1 cup',
    default_serving_grams: 195,
    default_nutrients: {
      calories: 240,
      protein_g: 5.3,
      carbs_g: 50,
      fat_g: 2,
    },
    portions: [
      {
        id: 'portion-3',
        food_id: 'mock-search-2',
        amount: 1,
        unit: 'cup',
        modifier: null,
        gram_weight: 195,
        label: '1 cup (195g)',
        is_default: true,
      },
    ],
    is_custom: false,
    is_favorite: false,
  },
  {
    id: 'mock-search-3',
    source: 'manual',
    source_food_id: null,
    custom_food_id: 'custom-food-1',
    name: 'My Special Protein Shake',
    category: 'Custom food',
    data_version: 'usda_fdc_2026_04_mvp',
    calories_per_100g: 450,
    protein_g_per_100g: 80,
    carbs_g_per_100g: 10,
    fat_g_per_100g: 5,
    default_serving_label: '1 scoop',
    default_serving_grams: 35,
    default_nutrients: {
      calories: 157,
      protein_g: 28,
      carbs_g: 3.5,
      fat_g: 1.7,
    },
    portions: [
      {
        id: 'portion-4',
        food_id: 'custom-food-1',
        amount: 1,
        unit: 'scoop',
        modifier: null,
        gram_weight: 35,
        label: '1 scoop (35g)',
        is_default: true,
      },
    ],
    is_custom: true,
    is_favorite: false,
  },
];
