import { Colors } from './tokens';

export const themes = {
  dark: {
    background: Colors.bg,
    surface: Colors.surface,
    card: Colors.card,
    cardHover: Colors.cardHover,
    border: Colors.border,
    borderLight: Colors.borderLight,
    accent: Colors.accent,
    accentSoft: Colors.accentSoft,
    accentMuted: Colors.accentMuted,
    green: Colors.green,
    greenMuted: Colors.greenMuted,
    orange: Colors.orange,
    orangeMuted: Colors.orangeMuted,
    red: Colors.red,
    redMuted: Colors.redMuted,
    blue: Colors.blue,
    blueMuted: Colors.blueMuted,
    text: Colors.text,
    textStrong: Colors.white,
    textSecondary: Colors.textSecondary,
    textSubtle: Colors.dim,
    muted: Colors.muted,
    dim: Colors.dim,
    inputPlaceholder: Colors.dim,
    overlay: 'rgba(4, 4, 10, 0.72)',
    webBackdrop: '#06060B',
    webShadow: 'rgba(0,0,0,0.8)',
  },
  light: {
    background: '#FFFFFF',
    surface: '#F6F7FB',
    card: '#FFFFFF',
    cardHover: '#F0F2F8',
    border: '#D7DBE8',
    borderLight: '#E7EAF2',
    accent: Colors.accent,
    accentSoft: Colors.accentSoft,
    accentMuted: 'rgba(124, 92, 252, 0.12)',
    green: '#1B8F62',
    greenMuted: 'rgba(27, 143, 98, 0.1)',
    orange: '#D86122',
    orangeMuted: 'rgba(216, 97, 34, 0.1)',
    red: '#C43858',
    redMuted: 'rgba(196, 56, 88, 0.1)',
    blue: '#2B79D6',
    blueMuted: 'rgba(43, 121, 214, 0.1)',
    text: '#171925',
    textStrong: '#0F1320',
    textSecondary: '#414760',
    textSubtle: '#7C849A',
    muted: '#6B728A',
    dim: '#8B90A6',
    inputPlaceholder: '#98A0B3',
    overlay: 'rgba(15, 23, 42, 0.16)',
    webBackdrop: '#EDF1F7',
    webShadow: 'rgba(15,23,42,0.14)',
  },
} as const;

export type ThemeName = keyof typeof themes;
export type ThemeColors = (typeof themes)[ThemeName];
export type ThemeModePreference = 'system' | ThemeName;
