import { createTokens } from 'tamagui';

export const Colors = {
  bg: '#0A0A0F',
  surface: '#12121A',
  card: '#1A1A26',
  cardHover: '#1F1F30',
  border: '#2A2A3A',
  borderLight: '#353548',
  accent: '#7C5CFC',
  accentSoft: '#4F3AA8',
  accentMuted: 'rgba(124, 92, 252, 0.15)',
  green: '#2FE5A3',
  greenMuted: 'rgba(47, 229, 163, 0.12)',
  orange: '#FF7A3D',
  orangeMuted: 'rgba(255, 122, 61, 0.12)',
  red: '#FF4D6D',
  redMuted: 'rgba(255, 77, 109, 0.12)',
  blue: '#4DA6FF',
  blueMuted: 'rgba(77, 166, 255, 0.12)',
  text: '#F0F0FF',
  textSecondary: '#B8B8D0',
  muted: '#8888AA',
  dim: '#555570',
  white: '#FFFFFF',
  black: '#000000',
  gradientAccent: ['#7C5CFC', '#4F3AA8'] as const,
  gradientGreen: ['#2FE5A3', '#1AB87E'] as const,
  gradientOrange: ['#FF7A3D', '#E5562A'] as const,
  gradientDark: ['#1A1A26', '#12121A'] as const,
} as const;

export const Spacing = {
  xs: 4,
  sm: 8,
  md: 12,
  lg: 16,
  xl: 20,
  xxl: 24,
  xxxl: 32,
} as const;

export const Radius = {
  sm: 8,
  md: 12,
  lg: 16,
  xl: 20,
  xxl: 24,
  full: 999,
} as const;

export const Typography = {
  fontDisplay: 'Georgia',
  fontBody: 'System',
  fontMono: 'Courier New',
  size: {
    xs: 11,
    sm: 13,
    md: 15,
    lg: 17,
    xl: 20,
    xxl: 24,
    xxxl: 30,
    display: 36,
  },
  weight: {
    regular: '400' as const,
    medium: '500' as const,
    semibold: '600' as const,
    bold: '700' as const,
    extrabold: '800' as const,
  },
} as const;

export const Shadow = {
  sm: {
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  md: {
    shadowColor: Colors.accent,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 6,
  },
  lg: {
    shadowColor: Colors.accent,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 10,
  },
} as const;

export const tokens = createTokens({
  color: {
    background: Colors.bg,
    surface: Colors.surface,
    card: Colors.card,
    cardHover: Colors.cardHover,
    border: Colors.border,
    borderLight: Colors.borderLight,
    accent: Colors.accent,
    accentSoft: Colors.accentSoft,
    accentMuted: Colors.accentMuted,
    green: Colors.green,
    greenMuted: Colors.greenMuted,
    orange: Colors.orange,
    orangeMuted: Colors.orangeMuted,
    red: Colors.red,
    redMuted: Colors.redMuted,
    blue: Colors.blue,
    blueMuted: Colors.blueMuted,
    text: Colors.text,
    textSecondary: Colors.textSecondary,
    muted: Colors.muted,
    dim: Colors.dim,
    white: Colors.white,
    black: Colors.black,
  },
  space: {
    0: 0,
    xs: Spacing.xs,
    sm: Spacing.sm,
    md: Spacing.md,
    true: Spacing.md,
    lg: Spacing.lg,
    xl: Spacing.xl,
    xxl: Spacing.xxl,
    xxxl: Spacing.xxxl,
  },
  size: {
    xs: 28,
    sm: 36,
    md: 44,
    true: 44,
    lg: 52,
    xl: 60,
  },
  radius: {
    0: 0,
    sm: Radius.sm,
    md: Radius.md,
    lg: Radius.lg,
    xl: Radius.xl,
    xxl: Radius.xxl,
    full: Radius.full,
  },
  zIndex: {
    xs: 0,
    sm: 1,
    md: 10,
    true: 10,
    lg: 100,
    xl: 1000,
  },
});
